import LandCard from "@/components/land-card";
import Image from "next/image";

export const items = [
  {
    name: "",
    tag: "",
    type: "",
    variant: "",
    image: "",
    sui: "",
    token: "",
    percentage: "",
    id: 1,
    label: "Item 1",
    color: "#f9f9f9",
    land: <></>,
  },
  {
    name: "",
    tag: "",
    type: "",
    variant: "",
    image: "",
    sui: "",
    token: "",
    percentage: "",
    id: 2,
    label: "Item 2",
    color: "#f9f9f9",
    land: <></>,
  },
  {
    name: "",
    tag: "",
    type: "",
    variant: "",
    image: "",
    sui: "",
    token: "",
    percentage: "",
    id: 3,
    label: "Item 3",
    color: "#f9f9f9",
    land: <></>,
  },
  {
    name: "",
    tag: "",
    type: "",
    variant: "",
    image: "",
    sui: "",
    token: "",
    percentage: "",
    id: 4,
    label: "Item 4",
    color: "#f9f9f9",
    land: <></>,
  },
  {
    name: "",
    tag: "",
    type: "",
    variant: "",
    image: "",
    sui: "",
    token: "",
    percentage: "",
    id: 5,
    label: "Item 5",
    color: "#f9f9f9",
    land: <></>,
  },
  {
    name: "",
    tag: "",
    type: "",
    variant: "",
    image: "",
    sui: "",
    token: "",
    percentage: "",
    id: 6,
    label: "Item 6",
    color: "#f9f9f9",
    land: <></>,
  },
  {
    name: "",
    tag: "",
    type: "",
    variant: "",
    image: "",
    sui: "",
    token: "",
    percentage: "",
    id: 7,
    label: "Item 7",
    color: "#f9f9f9",
    land: <></>,
  },
  {
    name: "",
    tag: "",
    type: "",
    variant: "",
    image: "",
    sui: "",
    token: "",
    percentage: "",
    id: 8,
    label: "Item 8",
    color: "#f9f9f9",
    land: <></>,
  },
  {
    name: "",
    tag: "",
    type: "",
    variant: "",
    image: "",
    sui: "",
    token: "",
    percentage: "",
    id: 9,
    label: "Item 9",
    color: "#f9f9f9",
    land: <></>,
  },
  {
    name: "",
    tag: "",
    type: "",
    variant: "",
    image: "",
    sui: "",
    token: "",
    percentage: "",
    id: 10,
    label: "Item 10",
    color: "#f9f9f9",
    land: <></>,
  },
  {
    name: "",
    tag: "",
    type: "",
    variant: "",
    image: "",
    sui: "",
    token: "",
    percentage: "",
    id: 11,
    label: "Item 11",
    color: "#f9f9f9",
    land: <></>,
  },
  {
    name: "",
    tag: "",
    type: "",
    variant: "",
    image: "",
    sui: "",
    token: "",
    percentage: "",
    id: 12,
    label: "Item 12",
    color: "#f9f9f9",
    land: <></>,
  },
  {
    name: "",
    tag: "",
    type: "",
    variant: "",
    image: "",
    sui: "",
    token: "",
    percentage: "",
    id: 13,
    label: "Item 13",
    color: "#f9f9f9",
    land: <></>,
  },
  {
    name: "",
    tag: "",
    type: "",
    variant: "",
    image: "",
    sui: "",
    token: "",
    percentage: "",
    id: 14,
    label: "Item 14",
    color: "#f9f9f9",
    land: <></>,
  },
  {
    name: "",
    tag: "",
    type: "",
    variant: "",
    image: "",
    sui: "",
    token: "",
    percentage: "",
    id: 15,
    label: "Item 15",
    color: "#f9f9f9",
    land: (
      <>
        <Image
          src={"/assets/stones/stone-1.png"}
          alt={"stone"}
          height={500}
          width={500}
          unoptimized
          className="min-[140px] lg:min-w-[150px]"
        />
      </>
    ),
  },
  {
    name: "Konoha",
    tag: "naruto",
    type: "A",
    variant: "platinum",
    image: "/assets/lands/image-1.png",
    sui: 31,
    token: 12,
    percentage: 1.4,
    id: 16,
    label: "Item 16",
    color: "#DE5995",
    land: (
      <>
        <LandCard
          className=""
          image={"/assets/lands/image-1.png"}
          name={"Konoha"}
          tag={"@naruto"}
          sui={31}
          token={12}
          percentage={1.4}
          imageClassName={
            "max-w-[200px] lg:max-w-[90px] w-full flex justify-center items-center"
          }
          type={"A"}
          variant={"platinum"}
        />
      </>
    ),
  },
  {
    name: "",
    tag: "",
    type: "",
    variant: "",
    image: "",
    sui: "",
    token: "",
    percentage: "",
    id: 17,
    label: "Item 17",
    color: "#f9f9f9",
    land: <></>,
  },
  {
    name: "Planet Namek",
    tag: "@suiyan",
    type: "A",
    variant: "platinum",
    image: "/assets/lands/image-3.png",
    sui: 42,
    token: 30,
    percentage: 1.8,
    id: 18,
    label: "Item 18",
    color: "#DE5995",
    land: (
      <>
        <LandCard
          className={""}
          image={"/assets/lands/image-3.png"}
          name={"Planet Namek"}
          tag={"@suiyan"}
          sui={42}
          token={30}
          percentage={1.8}
          imageClassName={
            "max-w-[200px] lg:max-w-[90px] w-full flex justify-center items-center"
          }
          type={"A"}
          variant={"platinum"}
        />
      </>
    ),
  },
  {
    name: "",
    tag: "",
    type: "",
    variant: "",
    image: "",
    sui: "",
    token: "",
    percentage: "",
    id: 19,
    label: "Item 19",
    color: "#f9f9f9",
    land: <></>,
  },
  {
    name: "",
    tag: "",
    type: "",
    variant: "",
    image: "",
    sui: "",
    token: "",
    percentage: "",
    id: 20,
    label: "Item 20",
    color: "#f9f9f9",
    land: <></>,
  },
  {
    name: "",
    tag: "",
    type: "",
    variant: "",
    image: "",
    sui: "",
    token: "",
    percentage: "",
    id: 21,
    label: "Item 21",
    color: "#f9f9f9",
    land: <></>,
  },
  {
    name: "",
    tag: "",
    type: "",
    variant: "",
    image: "",
    sui: "",
    token: "",
    percentage: "",
    id: 22,
    label: "Item 22",
    color: "#f9f9f9",
    land: <></>,
  },
  {
    name: "",
    tag: "",
    type: "",
    variant: "",
    image: "",
    sui: "",
    token: "",
    percentage: "",
    id: 23,
    label: "Item 23",
    color: "#f9f9f9",
    land: <></>,
  },
  {
    name: "",
    tag: "",
    type: "",
    variant: "",
    image: "",
    sui: "",
    token: "",
    percentage: "",
    id: 24,
    label: "Item 24",
    color: "#f9f9f9",
    land: <></>,
  },
  {
    name: "",
    tag: "",
    type: "",
    variant: "",
    image: "",
    sui: "",
    token: "",
    percentage: "",
    id: 25,
    label: "Item 25",
    color: "#f9f9f9",
    land: <></>,
  },
  {
    name: "",
    tag: "",
    type: "",
    variant: "",
    image: "",
    sui: "",
    token: "",
    percentage: "",
    id: 26,
    label: "Item 26",
    color: "#f9f9f9",
    land: <></>,
  },
  {
    name: "",
    tag: "",
    type: "",
    variant: "",
    image: "",
    sui: "",
    token: "",
    percentage: "",
    id: 27,
    label: "Item 27",
    color: "#f9f9f9",
    land: <></>,
  },
  {
    name: "",
    tag: "",
    type: "",
    variant: "",
    image: "",
    sui: "",
    token: "",
    percentage: "",
    id: 28,
    label: "Item 28",
    color: "#f9f9f9",
    land: <></>,
  },
  {
    name: "Mirai Land",
    tag: "@studiomirai",
    type: "A",
    variant: "platinum",
    image: "/assets/lands/image-2.png",
    sui: 80,
    token: 47,
    percentage: 1.1,
    id: 29,
    label: "Item 29",
    color: "#DE5995",
    land: (
      <>
        <LandCard
          className="max-w-[220px] flex justify-center items-center"
          image={"/assets/lands/image-2.png"}
          name={"Mirai Land"}
          tag={"@studiomirai"}
          sui={80}
          token={47}
          percentage={1.1}
          imageClassName={
            "max-w-[200px] lg:max-w-[90px] w-full flex justify-center items-center"
          }
          type={"A"}
          variant={"platinum"}
        />
      </>
    ),
  },
  {
    name: "",
    tag: "",
    type: "",
    variant: "",
    image: "",
    sui: "",
    token: "",
    percentage: "",
    id: 30,
    label: "Item 30",
    color: "#f9f9f9",
    land: <></>,
  },
  {
    name: "",
    tag: "",
    type: "",
    variant: "",
    image: "",
    sui: "",
    token: "",
    percentage: "",
    id: 31,
    label: "Item 31",
    color: "#f9f9f9",
    land: <></>,
  },
  {
    name: "",
    tag: "",
    type: "",
    variant: "",
    image: "",
    sui: "",
    token: "",
    percentage: "",
    id: 32,
    label: "Item 32",
    color: "#f9f9f9",
    land: <></>,
  },
  {
    name: "",
    tag: "",
    type: "",
    variant: "",
    image: "",
    sui: "",
    token: "",
    percentage: "",
    id: 33,
    label: "Item 33",
    color: "#f9f9f9",
    land: <></>,
  },
  {
    name: "",
    tag: "",
    type: "",
    variant: "",
    image: "",
    sui: "",
    token: "",
    percentage: "",
    id: 34,
    label: "Item 34",
    color: "#f9f9f9",
    land: <></>,
  },
  {
    name: "",
    tag: "",
    type: "",
    variant: "",
    image: "",
    sui: "",
    token: "",
    percentage: "",
    id: 35,
    label: "Item 35",
    color: "#f9f9f9",
    land: <></>,
  },
  {
    name: "",
    tag: "",
    type: "",
    variant: "",
    image: "",
    sui: "",
    token: "",
    percentage: "",
    id: 36,
    label: "Item 36",
    color: "#f9f9f9",
    land: <></>,
  },
  {
    name: "",
    tag: "",
    type: "",
    variant: "",
    image: "",
    sui: "",
    token: "",
    percentage: "",
    id: 37,
    label: "Item 37",
    color: "#f9f9f9",
    land: <></>,
  },
  {
    name: "",
    tag: "",
    type: "",
    variant: "",
    image: "",
    sui: "",
    token: "",
    percentage: "",
    id: 38,
    label: "Item 38",
    color: "#f9f9f9",
    land: <></>,
  },
  {
    name: "Pink Panther",
    tag: "0x1412…4120",
    type: "A",
    variant: "platinum",
    image: "/assets/lands/image-4.png",
    sui: 37,
    token: 22,
    percentage: 1.3,
    id: 39,
    label: "Item 39",
    color: "#DE5995",
    land: (
      <>
        <LandCard
          className={""}
          image={"/assets/lands/image-4.png"}
          name={"Pink Panther"}
          tag={"0x1412…4120"}
          sui={37}
          token={22}
          percentage={1.3}
          imageClassName={"max-w-[200px] lg:max-w-[90px] w-full"}
          type={"A"}
          variant={"platinum"}
        />
      </>
    ),
  },
  {
    name: "Cherry Land",
    tag: "@wara",
    type: "A",
    variant: "platinum",
    image: "/assets/lands/image-6.png",
    sui: 88,
    token: 12,
    percentage: 1.14,
    id: 40,
    label: "Item 40",
    color: "#DE5995",
    land: (
      <>
        <LandCard
          className="hover:z-[2]"
          image={"/assets/lands/image-6.png"}
          name={"Cherry Land"}
          tag={"@wara"}
          sui={88}
          token={12}
          percentage={1.14}
          imageClassName={"max-w-[200px] lg:max-w-[90px] w-full"}
          type={"A"}
          variant={"platinum"}
        />
      </>
    ),
  },
  {
    name: "",
    tag: "",
    type: "",
    variant: "",
    image: "",
    sui: "",
    token: "",
    percentage: "",
    id: 41,
    label: "Item 41",
    color: "#f9f9f9",
    land: <></>,
  },
  {
    name: "",
    tag: "",
    type: "",
    variant: "",
    image: "",
    sui: "",
    token: "",
    percentage: "",
    id: 42,
    label: "Item 42",
    color: "#f9f9f9",
    land: <></>,
  },
  {
    name: "",
    tag: "",
    type: "",
    variant: "",
    image: "",
    sui: "",
    token: "",
    percentage: "",
    id: 43,
    label: "Item 43",
    color: "#f9f9f9",
    land: <></>,
  },
  {
    name: "",
    tag: "",
    type: "",
    variant: "",
    image: "",
    sui: "",
    token: "",
    percentage: "",
    id: 44,
    label: "Item 44",
    color: "#f9f9f9",
    land: <></>,
  },
  {
    name: "Loki's Hideout",
    tag: "@wallstreetbets",
    type: "C",
    variant: "emerald",
    image: "/assets/lands/image-12.png",
    sui: 12,
    token: 6,
    percentage: 1.4,
    id: 45,
    label: "Item 45",
    color: "#C6E67A",
    land: (
      <>
        <LandCard
          className=""
          image={"/assets/lands/image-12.png"}
          name={"Loki's Hideout"}
          tag={"@wallstreetbets"}
          sui={12}
          token={6}
          percentage={1.4}
          imageClassName={"max-w-[200px] lg:max-w-[90px] w-full"}
          type={"C"}
          variant={"emerald"}
        />
      </>
    ),
  },
  {
    name: "",
    tag: "",
    type: "",
    variant: "",
    image: "",
    sui: "",
    token: "",
    percentage: "",
    id: 46,
    label: "Item 46",
    color: "#f9f9f9",
    land: <></>,
  },
  {
    name: "",
    tag: "",
    type: "",
    variant: "",
    image: "",
    sui: "",
    token: "",
    percentage: "",
    id: 47,
    label: "Item 47",
    color: "#f9f9f9",
    land: <></>,
  },
  {
    name: "",
    tag: "",
    type: "",
    variant: "",
    image: "",
    sui: "",
    token: "",
    percentage: "",
    id: 48,
    label: "Item 48",
    color: "#f9f9f9",
    land: <></>,
  },
  {
    name: "",
    tag: "",
    type: "",
    variant: "",
    image: "",
    sui: "",
    token: "",
    percentage: "",
    id: 49,
    label: "Item 49",
    color: "#f9f9f9",
    land: <></>,
  },
  {
    name: "",
    tag: "",
    type: "",
    variant: "",
    image: "",
    sui: "",
    token: "",
    percentage: "",
    id: 50,
    label: "Item 50",
    color: "#f9f9f9",
    land: <></>,
  },
  {
    name: "Cherry Land",
    tag: "@wara",
    type: "A",
    variant: "platinum",
    image: "/assets/lands/image-6.png",
    sui: 88,
    token: 12,
    percentage: 1.14,
    id: 51,
    label: "Item 51",
    color: "#DE5995",
    land: (
      <>
        <LandCard
          className="hover:z-[2]"
          image={"/assets/lands/image-6.png"}
          name={"Cherry Land"}
          tag={"@wara"}
          sui={88}
          token={12}
          percentage={1.14}
          imageClassName={"max-w-[200px] lg:max-w-[90px] w-full"}
          type={"A"}
          variant={"platinum"}
        />
      </>
    ),
  },
  {
    name: "",
    tag: "",
    type: "",
    variant: "",
    image: "",
    sui: "",
    token: "",
    percentage: "",
    id: 52,
    label: "Item 52",
    color: "#f9f9f9",
    land: <></>,
  },
  {
    name: "",
    tag: "",
    type: "",
    variant: "",
    image: "",
    sui: "",
    token: "",
    percentage: "",
    id: 53,
    label: "Item 53",
    color: "#f9f9f9",
    land: <></>,
  },
  {
    name: "",
    tag: "",
    type: "",
    variant: "",
    image: "",
    sui: "",
    token: "",
    percentage: "",
    id: 54,
    label: "Item 54",
    color: "#f9f9f9",
    land: <></>,
  },
  {
    name: "",
    tag: "",
    type: "",
    variant: "",
    image: "",
    sui: "",
    token: "",
    percentage: "",
    id: 55,
    label: "Item 55",
    color: "#f9f9f9",
    land: <></>,
  },
  {
    name: "Emerald City of Oz",
    tag: "@mystenlabs",
    type: "C",
    variant: "emerald",
    image: "/assets/lands/image-13.png",
    sui: 12,
    token: 6,
    percentage: 1.4,
    id: 56,
    label: "Item 56",
    color: "#C6E67A",
    land: (
      <>
        <LandCard
          className=""
          image={"/assets/lands/image-13.png"}
          name={"Emerald City of Oz"}
          tag={"@mystenlabs"}
          sui={12}
          token={6}
          percentage={1.4}
          imageClassName={"max-w-[200px] lg:max-w-[90px] w-full"}
          type={"C"}
          variant={"emerald"}
        />
      </>
    ),
  },
  {
    name: "",
    tag: "",
    type: "",
    variant: "",
    image: "",
    sui: "",
    token: "",
    percentage: "",
    id: 57,
    label: "Item 57",
    color: "#f9f9f9",
    land: <></>,
  },
  {
    name: "",
    tag: "",
    type: "",
    variant: "",
    image: "",
    sui: "",
    token: "",
    percentage: "",
    id: 58,
    label: "Item 58",
    color: "#f9f9f9",
    land: <></>,
  },
  {
    name: "",
    tag: "",
    type: "",
    variant: "",
    image: "",
    sui: "",
    token: "",
    percentage: "",
    id: 59,
    label: "Item 59",
    color: "#f9f9f9",
    land: <></>,
  },
  {
    name: "",
    tag: "",
    type: "",
    variant: "",
    image: "",
    sui: "",
    token: "",
    percentage: "",
    id: 60,
    label: "Item 60",
    color: "#f9f9f9",
    land: <></>,
  },
  {
    name: "",
    tag: "",
    type: "",
    variant: "",
    image: "",
    sui: "",
    token: "",
    percentage: "",
    id: 61,
    label: "Item 61",
    color: "#f9f9f9",
    land: <></>,
  },
  {
    name: "",
    tag: "",
    type: "",
    variant: "",
    image: "",
    sui: "",
    token: "",
    percentage: "",
    id: 62,
    label: "Item 62",
    color: "#f9f9f9",
    land: <></>,
  },
  {
    name: "",
    tag: "",
    type: "",
    variant: "",
    image: "",
    sui: "",
    token: "",
    percentage: "",
    id: 63,
    label: "Item 63",
    color: "#f9f9f9",
    land: <></>,
  },
  {
    name: "AEON land",
    tag: "@000",
    type: "A",
    variant: "platinum",
    image: "/assets/lands/image-7.png",
    sui: 144,
    token: 53,
    percentage: 2.01,
    id: 64,
    label: "Item 64",
    color: "#DE5995",
    land: (
      <>
        <LandCard
          className="hover:z-[2]"
          image={"/assets/lands/image-7.png"}
          name={"AEON land"}
          tag={"@000"}
          sui={144}
          token={53}
          percentage={2.01}
          imageClassName={"max-w-[200px] lg:max-w-[90px] w-full"}
          type={"A"}
          variant={"platinum"}
        />
      </>
    ),
  },
  {
    name: "AEON land V2",
    tag: "@000",
    type: "A",
    variant: "platinum",
    image: "/assets/lands/image-1.png",
    sui: 144,
    token: 53,
    percentage: 2.01,
    id: 65,
    label: "Item 65",
    color: "#DE5995",
    land: (
      <>
        <LandCard
          className="hover:z-[2]"
          image={"/assets/lands/image-1.png"}
          name={"AEON land V2"}
          tag={"@000"}
          sui={144}
          token={53}
          percentage={2.01}
          imageClassName={"max-w-[200px] lg:max-w-[90px] w-full"}
          type={"A"}
          variant={"platinum"}
        />
      </>
    ),
  },
  {
    name: "",
    tag: "",
    type: "",
    variant: "",
    image: "",
    sui: "",
    token: "",
    percentage: "",
    id: 66,
    label: "Item 66",
    color: "#f9f9f9",
    land: <></>,
  },
  {
    name: "Shang Chi",
    tag: "@kotaro",
    type: "D",
    variant: "gold",
    image: "/assets/lands/image-14.png",
    sui: 12,
    token: 6,
    percentage: 1.4,
    id: 67,
    label: "Item 67",
    color: "#7AE67F",
    land: (
      <>
        <LandCard
          className=""
          image={"/assets/lands/image-14.png"}
          name={"Shang Chi"}
          tag={"@kotaro"}
          sui={12}
          token={6}
          percentage={1.4}
          imageClassName={"max-w-[200px] lg:max-w-[90px] w-full"}
          type={"D"}
          variant={"gold"}
        />
      </>
    ),
  },
  {
    name: "",
    tag: "",
    type: "",
    variant: "",
    image: "",
    sui: "",
    token: "",
    percentage: "",
    id: 68,
    label: "Item 68",
    color: "#f9f9f9",
    land: <></>,
  },
  {
    name: "",
    tag: "",
    type: "",
    variant: "",
    image: "",
    sui: "",
    token: "",
    percentage: "",
    id: 69,
    label: "Item 69",
    color: "#f9f9f9",
    land: <></>,
  },
  {
    name: "",
    tag: "",
    type: "",
    variant: "",
    image: "",
    sui: "",
    token: "",
    percentage: "",
    id: 70,
    label: "Item 70",
    color: "#f9f9f9",
    land: <></>,
  },
  {
    name: "",
    tag: "",
    type: "",
    variant: "",
    image: "",
    sui: "",
    token: "",
    percentage: "",
    id: 71,
    label: "Item 71",
    color: "#f9f9f9",
    land: <></>,
  },
  {
    name: "",
    tag: "",
    type: "",
    variant: "",
    image: "",
    sui: "",
    token: "",
    percentage: "",
    id: 72,
    label: "Item 72",
    color: "#f9f9f9",
    land: <></>,
  },
  {
    name: "",
    tag: "",
    type: "",
    variant: "",
    image: "",
    sui: "",
    token: "",
    percentage: "",
    id: 73,
    label: "Item 73",
    color: "#f9f9f9",
    land: <></>,
  },
  {
    name: "",
    tag: "",
    type: "",
    variant: "",
    image: "",
    sui: "",
    token: "",
    percentage: "",
    id: 74,
    label: "Item 74",
    color: "#f9f9f9",
    land: <></>,
  },
  {
    name: "",
    tag: "",
    type: "",
    variant: "",
    image: "",
    sui: "",
    token: "",
    percentage: "",
    id: 75,
    label: "Item 75",
    color: "#f9f9f9",
    land: <></>,
  },
  {
    name: "",
    tag: "",
    type: "",
    variant: "",
    image: "",
    sui: "",
    token: "",
    percentage: "",
    id: 76,
    label: "Item 76",
    color: "#f9f9f9",
    land: <></>,
  },
  {
    name: "Panda Express",
    tag: "@pandakitchen",
    type: "D",
    variant: "gold",
    image: "/assets/lands/image-8.png",
    sui: 31,
    token: 12,
    percentage: 1.1,
    id: 77,
    label: "Item 77",
    color: "#7AE67F",
    land: (
      <>
        <LandCard
          className=""
          image={"/assets/lands/image-8.png"}
          name={"Panda Express"}
          tag={"@pandakitchen"}
          sui={31}
          token={12}
          percentage={1.1}
          imageClassName={"max-w-[200px] lg:max-w-[90px] w-full"}
          type={"D"}
          variant={"gold"}
        />
      </>
    ),
  },
  {
    name: "",
    tag: "",
    type: "",
    variant: "",
    image: "",
    sui: "",
    token: "",
    percentage: "",
    id: 78,
    label: "Item 78",
    color: "#f9f9f9",
    land: <></>,
  },
  {
    name: "",
    tag: "",
    type: "",
    variant: "",
    image: "",
    sui: "",
    token: "",
    percentage: "",
    id: 79,
    label: "Item 79",
    color: "#f9f9f9",
    land: <></>,
  },
  {
    name: "Bambooman",
    tag: "@suifrens",
    type: "D",
    variant: "gold",
    image: "/assets/lands/image-15.png",
    sui: 12,
    token: 6,
    percentage: 1.4,
    id: 80,
    label: "Item 80",
    color: "#7AE67F",
    land: (
      <>
        {" "}
        <LandCard
          className=""
          image={"/assets/lands/image-15.png"}
          name={"Bambooman"}
          tag={"@suifrens"}
          sui={12}
          token={6}
          percentage={1.4}
          imageClassName={"max-w-[200px] lg:max-w-[90px] w-full"}
          type={"D"}
          variant={"gold"}
        />
      </>
    ),
  },
  {
    name: "",
    tag: "",
    type: "",
    variant: "",
    image: "",
    sui: "",
    token: "",
    percentage: "",
    id: 81,
    label: "Item 81",
    color: "#f9f9f9",
    land: <></>,
  },
  {
    name: "",
    tag: "",
    type: "",
    variant: "",
    image: "",
    sui: "",
    token: "",
    percentage: "",
    id: 82,
    label: "Item 82",
    color: "#f9f9f9",
    land: <></>,
  },
  {
    name: "",
    tag: "",
    type: "",
    variant: "",
    image: "",
    sui: "",
    token: "",
    percentage: "",
    id: 83,
    label: "Item 83",
    color: "#f9f9f9",
    land: <></>,
  },
  {
    name: "",
    tag: "",
    type: "",
    variant: "",
    image: "",
    sui: "",
    token: "",
    percentage: "",
    id: 84,
    label: "Item 84",
    color: "#f9f9f9",
    land: <></>,
  },
  {
    name: "",
    tag: "",
    type: "",
    variant: "",
    image: "",
    sui: "",
    token: "",
    percentage: "",
    id: 85,
    label: "Item 85",
    color: "#f9f9f9",
    land: <></>,
  },
  {
    name: "",
    tag: "",
    type: "",
    variant: "",
    image: "",
    sui: "",
    token: "",
    percentage: "",
    id: 86,
    label: "Item 86",
    color: "#f9f9f9",
    land: <></>,
  },
  {
    name: "Zen's Tropics V2",
    tag: "@zenfrogs",
    type: "B",
    variant: "diamond",
    image: "/assets/lands/image-9.png",
    sui: 12,
    token: 6,
    percentage: 1.4,
    id: 87,
    label: "Item 87",
    color: "#DE9B0B",
    land: (
      <>
        <LandCard
          className=""
          image={"/assets/lands/image-9.png"}
          name={"Zen's Tropics V2"}
          tag={"@zenfrogs"}
          sui={12}
          token={6}
          percentage={1.4}
          imageClassName={"max-w-[200px] lg:max-w-[90px] w-full"}
          type={"B"}
          variant={"diamond"}
        />
      </>
    ),
  },
  {
    name: "Ancient Egypt V2",
    tag: "@adeniyi",
    type: "B",
    variant: "diamond",
    image: "/assets/lands/image-10.png",
    sui: 12,
    token: 6,
    percentage: 1.4,
    id: 88,
    label: "Item 88",
    color: "#DE9B0B",
    land: (
      <>
        <LandCard
          className=""
          image={"/assets/lands/image-10.png"}
          name={"Ancient Egypt V2"}
          tag={"@adeniyi"}
          sui={12}
          token={6}
          percentage={1.4}
          imageClassName={"max-w-[200px] lg:max-w-[90px] w-full"}
          type={"B"}
          variant={"diamond"}
        />
      </>
    ),
  },
  {
    name: "",
    tag: "",
    type: "",
    variant: "",
    image: "",
    sui: "",
    token: "",
    percentage: "",
    id: 89,
    label: "Item 89",
    color: "#f9f9f9",
    land: <></>,
  },
  {
    name: "",
    tag: "",
    type: "",
    variant: "",
    image: "",
    sui: "",
    token: "",
    percentage: "",
    id: 90,
    label: "Item 90",
    color: "#f9f9f9",
    land: <></>,
  },
  {
    name: "",
    tag: "",
    type: "",
    variant: "",
    image: "",
    sui: "",
    token: "",
    percentage: "",
    id: 91,
    label: "Item 91",
    color: "#f9f9f9",
    land: <></>,
  },
  {
    name: "",
    tag: "",
    type: "",
    variant: "",
    image: "",
    sui: "",
    token: "",
    percentage: "",
    id: 92,
    label: "Item 92",
    color: "#f9f9f9",
    land: <></>,
  },
  {
    name: "",
    tag: "",
    type: "",
    variant: "",
    image: "",
    sui: "",
    token: "",
    percentage: "",
    id: 93,
    label: "Item 93",
    color: "#f9f9f9",
    land: <></>,
  },
  {
    name: "",
    tag: "",
    type: "",
    variant: "",
    image: "",
    sui: "",
    token: "",
    percentage: "",
    id: 94,
    label: "Item 94",
    color: "#f9f9f9",
    land: <></>,
  },
  {
    name: "",
    tag: "",
    type: "",
    variant: "",
    image: "",
    sui: "",
    token: "",
    percentage: "",
    id: 95,
    label: "Item 95",
    color: "#f9f9f9",
    land: <></>,
  },
  {
    name: "",
    tag: "",
    type: "",
    variant: "",
    image: "",
    sui: "",
    token: "",
    percentage: "",
    id: 96,
    label: "Item 96",
    color: "#f9f9f9",
    land: <></>,
  },
  {
    name: "",
    tag: "",
    type: "",
    variant: "",
    image: "",
    sui: "",
    token: "",
    percentage: "",
    id: 97,
    label: "Item 97",
    color: "#f9f9f9",
    land: <></>,
  },
  {
    name: "",
    tag: "",
    type: "",
    variant: "",
    image: "",
    sui: "",
    token: "",
    percentage: "",
    id: 98,
    label: "Item 98",
    color: "#f9f9f9",
    land: <></>,
  },
  {
    name: "",
    tag: "",
    type: "",
    variant: "",
    image: "",
    sui: "",
    token: "",
    percentage: "",
    id: 99,
    label: "Item 99",
    color: "#f9f9f9",
    land: <></>,
  },
  {
    name: "",
    tag: "",
    type: "",
    variant: "",
    image: "",
    sui: "",
    token: "",
    percentage: "",
    id: 100,
    label: "Item 100",
    color: "#f9f9f9",
    land: <></>,
  },
  {
    name: "Zen's Tropics",
    tag: "@zenfrogs",
    type: "D",
    variant: "gold",
    image: "/assets/lands/image-11.png",
    sui: 12,
    token: 6,
    percentage: 1.4,
    id: 101,
    label: "Item 101",
    color: "#7AE67F",
    land: (
      <>
        <LandCard
          className=""
          image={"/assets/lands/image-11.png"}
          name={"Zen's Tropics"}
          tag={"@zenfrogs"}
          sui={12}
          token={6}
          percentage={1.4}
          imageClassName={"max-w-[200px] lg:max-w-[90px] w-full"}
          type={"D"}
          variant={"gold"}
        />
      </>
    ),
  },
  {
    name: "",
    tag: "",
    type: "",
    variant: "",
    image: "",
    sui: "",
    token: "",
    percentage: "",
    id: 102,
    label: "Item 102",
    color: "#f9f9f9",
    land: <></>,
  },
  {
    name: "Pls dont attacc me",
    tag: "@wade",
    type: "D",
    variant: "gold",
    image: "/assets/lands/image-16.png",
    sui: 12,
    token: 6,
    percentage: 1.4,
    id: 103,
    label: "Item 103",
    color: "#7AE67F",
    land: (
      <>
        <LandCard
          className=""
          image={"/assets/lands/image-16.png"}
          name={"Pls dont attacc me"}
          tag={"@wade"}
          sui={12}
          token={6}
          percentage={1.4}
          imageClassName={"max-w-[200px] lg:max-w-[90px] w-full"}
          type={"D"}
          variant={"gold"}
        />
      </>
    ),
  },
  {
    name: "",
    tag: "",
    type: "",
    variant: "",
    image: "",
    sui: "",
    token: "",
    percentage: "",
    id: 104,
    label: "Item 104",
    color: "#f9f9f9",
    land: <></>,
  },
  {
    name: "",
    tag: "",
    type: "",
    variant: "",
    image: "",
    sui: "",
    token: "",
    percentage: "",
    id: 105,
    label: "Item 105",
    color: "#f9f9f9",
    land: <></>,
  },
  {
    name: "",
    tag: "",
    type: "",
    variant: "",
    image: "",
    sui: "",
    token: "",
    percentage: "",
    id: 106,
    label: "Item 106",
    color: "#f9f9f9",
    land: <></>,
  },
  {
    name: "",
    tag: "",
    type: "",
    variant: "",
    image: "",
    sui: "",
    token: "",
    percentage: "",
    id: 107,
    label: "Item 107",
    color: "#f9f9f9",
    land: <></>,
  },
  {
    name: "",
    tag: "",
    type: "",
    variant: "",
    image: "",
    sui: "",
    token: "",
    percentage: "",
    id: 108,
    label: "Item 108",
    color: "#f9f9f9",
    land: <></>,
  },
  {
    name: "",
    tag: "",
    type: "",
    variant: "",
    image: "",
    sui: "",
    token: "",
    percentage: "",
    id: 109,
    label: "Item 109",
    color: "#f9f9f9",
    land: <></>,
  },
  {
    name: "",
    tag: "",
    type: "",
    variant: "",
    image: "",
    sui: "",
    token: "",
    percentage: "",
    id: 110,
    label: "Item 110",
    color: "#f9f9f9",
    land: <></>,
  },
  {
    name: "",
    tag: "",
    type: "",
    variant: "",
    image: "",
    sui: "",
    token: "",
    percentage: "",
    id: 111,
    label: "Item 111",
    color: "#f9f9f9",
    land: <></>,
  },
  {
    name: "",
    tag: "",
    type: "",
    variant: "",
    image: "",
    sui: "",
    token: "",
    percentage: "",
    id: 112,
    label: "Item 112",
    color: "#f9f9f9",
    land: <></>,
  },
  {
    name: "",
    tag: "",
    type: "",
    variant: "",
    image: "",
    sui: "",
    token: "",
    percentage: "",
    id: 113,
    label: "Item 113",
    color: "#f9f9f9",
    land: <></>,
  },
  {
    name: "",
    tag: "",
    type: "",
    variant: "",
    image: "",
    sui: "",
    token: "",
    percentage: "",
    id: 114,
    label: "Item 114",
    color: "#f9f9f9",
    land: <></>,
  },
  {
    name: "",
    tag: "",
    type: "",
    variant: "",
    image: "",
    sui: "",
    token: "",
    percentage: "",
    id: 115,
    label: "Item 115",
    color: "#f9f9f9",
    land: <></>,
  },
  {
    name: "KungFu Panda",
    tag: "0x95cc…1485",
    type: "D",
    variant: "gold",
    image: "/assets/lands/image-17.png",
    sui: 12,
    token: 6,
    percentage: 1.4,
    id: 116,
    label: "Item 116",
    color: "#7AE67F",
    land: (
      <>
        <LandCard
          className=""
          image={"/assets/lands/image-17.png"}
          name={"KungFu Panda"}
          tag={"0x95cc…1485"}
          sui={12}
          token={6}
          percentage={1.4}
          imageClassName={"max-w-[200px] lg:max-w-[90px] w-full"}
          type={"D"}
          variant={"gold"}
        />
      </>
    ),
  },
  {
    name: "",
    tag: "",
    type: "",
    variant: "",
    image: "",
    sui: "",
    token: "",
    percentage: "",
    id: 117,
    label: "Item 117",
    color: "#f9f9f9",
    land: <></>,
  },
  {
    name: "KungFu Panda 2",
    tag: "0x95cc…1485",
    type: "D",
    variant: "gold",
    image: "/assets/lands/image-18.png",
    sui: 12,
    token: 6,
    percentage: 1.4,
    id: 118,
    label: "Item 118",
    color: "#7AE67F",
    land: (
      <>
        <LandCard
          className=""
          image={"/assets/lands/image-18.png"}
          name={"KungFu Panda 2"}
          tag={"0x95cc…1485"}
          sui={12}
          token={6}
          percentage={1.4}
          imageClassName={"max-w-[200px] lg:max-w-[90px] w-full"}
          type={"D"}
          variant={"gold"}
        />
      </>
    ),
  },
  {
    name: "",
    tag: "",
    type: "",
    variant: "",
    image: "",
    sui: "",
    token: "",
    percentage: "",
    id: 119,
    label: "Item 119",
    color: "#f9f9f9",
    land: <></>,
  },
  {
    name: "",
    tag: "",
    type: "",
    variant: "",
    image: "",
    sui: "",
    token: "",
    percentage: "",
    id: 120,
    label: "Item 120",
    color: "#f9f9f9",
    land: <></>,
  },
  {
    name: "",
    tag: "",
    type: "",
    variant: "",
    image: "",
    sui: "",
    token: "",
    percentage: "",
    id: 121,
    label: "Item 121",
    color: "#f9f9f9",
    land: <></>,
  },
  {
    name: "",
    tag: "",
    type: "",
    variant: "",
    image: "",
    sui: "",
    token: "",
    percentage: "",
    id: 122,
    label: "Item 122",
    color: "#f9f9f9",
    land: <></>,
  },
  {
    name: "",
    tag: "",
    type: "",
    variant: "",
    image: "",
    sui: "",
    token: "",
    percentage: "",
    id: 123,
    label: "Item 123",
    color: "#f9f9f9",
    land: <></>,
  },
  {
    name: "",
    tag: "",
    type: "",
    variant: "",
    image: "",
    sui: "",
    token: "",
    percentage: "",
    id: 124,
    label: "Item 124",
    color: "#f9f9f9",
    land: <></>,
  },
  {
    name: "",
    tag: "",
    type: "",
    variant: "",
    image: "",
    sui: "",
    token: "",
    percentage: "",
    id: 125,
    label: "Item 125",
    color: "#f9f9f9",
    land: <></>,
  },
  {
    name: "",
    tag: "",
    type: "",
    variant: "",
    image: "",
    sui: "",
    token: "",
    percentage: "",
    id: 126,
    label: "Item 126",
    color: "#f9f9f9",
    land: <></>,
  },
  {
    name: "",
    tag: "",
    type: "",
    variant: "",
    image: "",
    sui: "",
    token: "",
    percentage: "",
    id: 127,
    label: "Item 127",
    color: "#f9f9f9",
    land: <></>,
  },
  {
    name: "",
    tag: "",
    type: "",
    variant: "",
    image: "",
    sui: "",
    token: "",
    percentage: "",
    id: 128,
    label: "Item 128",
    color: "#f9f9f9",
    land: <></>,
  },
  {
    name: "",
    tag: "",
    type: "",
    variant: "",
    image: "",
    sui: "",
    token: "",
    percentage: "",
    id: 129,
    label: "Item 129",
    color: "#f9f9f9",
    land: <></>,
  },
  {
    name: "",
    tag: "",
    type: "",
    variant: "",
    image: "",
    sui: "",
    token: "",
    percentage: "",
    id: 130,
    label: "Item 130",
    color: "#f9f9f9",
    land: <></>,
  },
  {
    name: "",
    tag: "",
    type: "",
    variant: "",
    image: "",
    sui: "",
    token: "",
    percentage: "",
    id: 131,
    label: "Item 131",
    color: "#f9f9f9",
    land: <></>,
  },
  {
    name: "",
    tag: "",
    type: "",
    variant: "",
    image: "",
    sui: "",
    token: "",
    percentage: "",
    id: 132,
    label: "Item 132",
    color: "#f9f9f9",
    land: <></>,
  },
  {
    name: "",
    tag: "",
    type: "",
    variant: "",
    image: "",
    sui: "",
    token: "",
    percentage: "",
    id: 133,
    label: "Item 133",
    color: "#f9f9f9",
    land: <></>,
  },
  {
    name: "",
    tag: "",
    type: "",
    variant: "",
    image: "",
    sui: "",
    token: "",
    percentage: "",
    id: 134,
    label: "Item 134",
    color: "#f9f9f9",
    land: <></>,
  },
  {
    name: "",
    tag: "",
    type: "",
    variant: "",
    image: "",
    sui: "",
    token: "",
    percentage: "",
    id: 135,
    label: "Item 135",
    color: "#f9f9f9",
    land: <></>,
  },
  {
    name: "",
    tag: "",
    type: "",
    variant: "",
    image: "",
    sui: "",
    token: "",
    percentage: "",
    id: 136,
    label: "Item 136",
    color: "#f9f9f9",
    land: <></>,
  },
  {
    name: "",
    tag: "",
    type: "",
    variant: "",
    image: "",
    sui: "",
    token: "",
    percentage: "",
    id: 137,
    label: "Item 137",
    color: "#f9f9f9",
    land: <></>,
  },
  {
    name: "",
    tag: "",
    type: "",
    variant: "",
    image: "",
    sui: "",
    token: "",
    percentage: "",
    id: 138,
    label: "Item 138",
    color: "#f9f9f9",
    land: <></>,
  },
  {
    name: "",
    tag: "",
    type: "",
    variant: "",
    image: "",
    sui: "",
    token: "",
    percentage: "",
    id: 139,
    label: "Item 139",
    color: "#f9f9f9",
    land: <></>,
  },
  {
    name: "",
    tag: "",
    type: "",
    variant: "",
    image: "",
    sui: "",
    token: "",
    percentage: "",
    id: 140,
    label: "Item 140",
    color: "#f9f9f9",
    land: <></>,
  },
  {
    name: "",
    tag: "",
    type: "",
    variant: "",
    image: "",
    sui: "",
    token: "",
    percentage: "",
    id: 141,
    label: "Item 141",
    color: "#f9f9f9",
    land: <></>,
  },
  {
    name: "",
    tag: "",
    type: "",
    variant: "",
    image: "",
    sui: "",
    token: "",
    percentage: "",
    id: 142,
    label: "Item 142",
    color: "#f9f9f9",
    land: <></>,
  },
  {
    name: "",
    tag: "",
    type: "",
    variant: "",
    image: "",
    sui: "",
    token: "",
    percentage: "",
    id: 143,
    label: "Item 143",
    color: "#f9f9f9",
    land: <></>,
  },
  {
    name: "",
    tag: "",
    type: "",
    variant: "",
    image: "",
    sui: "",
    token: "",
    percentage: "",
    id: 144,
    label: "Item 144",
    color: "#f9f9f9",
    land: <></>,
  },
  {
    name: "",
    tag: "",
    type: "",
    variant: "",
    image: "",
    sui: "",
    token: "",
    percentage: "",
    id: 145,
    label: "Item 145",
    color: "#f9f9f9",
    land: <></>,
  },
  {
    name: "",
    tag: "",
    type: "",
    variant: "",
    image: "",
    sui: "",
    token: "",
    percentage: "",
    id: 146,
    label: "Item 146",
    color: "#f9f9f9",
    land: <></>,
  },
  {
    name: "",
    tag: "",
    type: "",
    variant: "",
    image: "",
    sui: "",
    token: "",
    percentage: "",
    id: 147,
    label: "Item 147",
    color: "#f9f9f9",
    land: <></>,
  },
  {
    name: "",
    tag: "",
    type: "",
    variant: "",
    image: "",
    sui: "",
    token: "",
    percentage: "",
    id: 148,
    label: "Item 148",
    color: "#f9f9f9",
    land: <></>,
  },
  {
    name: "",
    tag: "",
    type: "",
    variant: "",
    image: "",
    sui: "",
    token: "",
    percentage: "",
    id: 149,
    label: "Item 149",
    color: "#f9f9f9",
    land: <></>,
  },
  {
    name: "",
    tag: "",
    type: "",
    variant: "",
    image: "",
    sui: "",
    token: "",
    percentage: "",
    id: 150,
    label: "Item 150",
    color: "#f9f9f9",
    land: <></>,
  },
  {
    name: "",
    tag: "",
    type: "",
    variant: "",
    image: "",
    sui: "",
    token: "",
    percentage: "",
    id: 151,
    label: "Item 151",
    color: "#f9f9f9",
    land: <></>,
  },
  {
    name: "",
    tag: "",
    type: "",
    variant: "",
    image: "",
    sui: "",
    token: "",
    percentage: "",
    id: 152,
    label: "Item 152",
    color: "#f9f9f9",
    land: <></>,
  },
  {
    name: "",
    tag: "",
    type: "",
    variant: "",
    image: "",
    sui: "",
    token: "",
    percentage: "",
    id: 153,
    label: "Item 152",
    color: "#f9f9f9",
    land: <></>,
  },
  {
    name: "",
    tag: "",
    type: "",
    variant: "",
    image: "",
    sui: "",
    token: "",
    percentage: "",
    id: 154,
    label: "Item 152",
    color: "#f9f9f9",
    land: <></>,
  },
  {
    name: "",
    tag: "",
    type: "",
    variant: "",
    image: "",
    sui: "",
    token: "",
    percentage: "",
    id: 155,
    label: "Item 152",
    color: "#f9f9f9",
    land: <></>,
  },
  {
    name: "",
    tag: "",
    type: "",
    variant: "",
    image: "",
    sui: "",
    token: "",
    percentage: "",
    id: 156,
    label: "Item 152",
    color: "#f9f9f9",
    land: <></>,
  },
];
